export default [
    { "_id": "A101", "title": "Propulsion Assignment", "course": "RS101", "available": "May 6 at 12:00am", "due": "May 13 at 11:59pm", "points": 100, "description": "This is the A101 description.", "submissionType": "ONLINE", "group": "ASSIGNMENTS", "gradeDisplay": "PERCENTAGE" },
    { "_id": "A102", "title": "Combustion Analysis", "course": "RS101", "available": "May 13 at 12:00am", "due": "May 20 at 11:59pm", "points": 100, "description": "This is the A102 description.", "submissionType": "ONLINE", "group": "ASSIGNMENTS", "gradeDisplay": "PERCENTAGE" },
    { "_id": "A103", "title": "Nozzle Design Project", "course": "RS101", "available": "May 20 at 12:00am", "due": "May 27 at 11:59pm", "points": 100, "description": "This is the A103 description.", "submissionType": "ONLINE", "group": "ASSIGNMENTS",	"gradeDisplay":"PERCENTAGE"},
    { "_id": "A201", "title": "Aerodynamics Quiz",	"course":"RS102","available":"May 27 at 12:00am","due":"June 3 at 11:59pm","points" :25,	"description":"This is the A201 description.","submissionType":"ONLINE","group":"ASSIGNMENTS","gradeDisplay":"PERCENTAGE"},
    { "_id": "A202",	"title":"Flow Analysis","course":"RS102","available":"June 3 at 12:00am","due":"June 10 at 11:59pm","points" :25,	"description":"This is the A202 description.","submissionType":"ONLINE","group":"ASSIGNMENTS","gradeDisplay":"PERCENTAGE"},
    { "_id": "A203",	"title":"Heating Analysis","course":"RS102","available":"June 10 at 12:00am","due":"June 17 at 11:59pm","points" :25,	"description":"This is the A203 description.","submissionType":"ONLINE","group":"ASSIGNMENTS","gradeDisplay":"PERCENTAGE"},
    { "_id": "A301", "title": "Structural Design Task", "course": "RS103", "available": "June 17 at 12:00am", "due": "June 24 at 11:59pm", "points": 50, "description": "This is the A301 description.", "submissionType": "ONLINE", "group": "ASSIGNMENTS","gradeDisplay":"PERCENTAGE" },
    { "_id": "A302", "title": "Orbital Calculations", "course": "RS103", "available":"June 24 at 12:00am","due":"July 1 at 11:59pm","points" :50,	"description":"This is the A302 description.","submissionType":"ONLINE","group":"ASSIGNMENTS","gradeDisplay":"PERCENTAGE"},
    { "_id": "A303", "title":"Systems Engineering Exam","course":"RS103","available":"July 8 at 12:00am","due":"July 8 at 11:59pm","points" :75,	"description":"This is the A303 description.","submissionType":"ONLINE","group":"ASSIGNMENTS","gradeDisplay":"PERCENTAGE"},
    { "_id": "A401", "title": "Organic Chemistry quiz", "course": "RS104", "available":"May 8 at 12:00am","due":"May 20 at 11:59pm","points" :20, "description": "This is the A401 description.", "submissionType": "ONLINE", "group": "ASSIGNMENTS","gradeDisplay":"PERCENTAGE" },
    { "_id": "A501", "title": "Inorganic Chemistry Lab", "course": "RS105",	"available":"April 20 at 12:00am","due":"May 8 at 11:59pm","points" :50, "description": "This is the A501 description.", "submissionType": "ONLINE", "group": "ASSIGNMENTS","gradeDisplay":"PERCENTAGE" },
    { "_id": "A601", "title": "Physical Chemistry Assignment", "course": "RS106", "available":"June 1 at 12:00am","due":"June 17 at 11:59pm","points" :35, "description": "This is the A601 description.", "submissionType": "ONLINE", "group": "ASSIGNMENTS","gradeDisplay":"PERCENTAGE" },
    { "_id": "A701", "title": "Ancient Languages Exam", "course": "RS107", "available":"May 24 at 12:00am","due":"June 1 at 11:59pm","points" :75,	"description":"This is the A701 description.","submissionType":"ONLINE","group":"ASSIGNMENTS","gradeDisplay":"PERCENTAGE"},
    { "_id": "A801", "title": "Diplomacy Essay", "course": "RS108",	"available":"May 15 at 12:00am","due":"May 30 at 11:59pm","points" :100,	"description":"This is the A801 description.","submissionType":"ONLINE","group":"ASSIGNMENTS","gradeDisplay":"PERCENTAGE"}
];